FIGHTERS_LIST = ['fighter_1','fighter_2',]
FEDERATIONS_LIST = ['federation_1','federation_2',]
MANAGERS_LIST = ['manager_1','manager_5']

# ,FIGHTERS_LIST=FIGHTERS_LIST,FEDERATIONS_LIST=FEDERATIONS_LIST,MANAGERS_LIST=MANAGERS_LIST
